version: '3'
services:
  juputer_notebook:
    build:
      context: ./
      dockerfile: Dockerfile
    image: spark_stack
    container_name: spark_stack_container
    ports:
      - 8889:8889 # local computer 8889 port for jupyter
      - 8080:8080 # master UI
      - 7070:7070 # spark master
      - "4040-4049:4040-4049" # for jobs
    volumes:
      - /home/:/home/
    network_mode: host
    environment: # these variables are passed to the container - same as -e option for docker run
      AWS_ACCESS_KEY_ID: $AWS_ACCESS_KEY_ID
      AWS_SECRET_ACCESS_KEY: $AWS_SECRET_ACCESS_KEY
